#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/psps_qa
#    username: psps_qa_user
#    password: psps
#  jpa:
#    hibernate:
#      ddl-auto: validate
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    database: mysql
#    show-sql: true